name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.4'
    - uses: actions/cache@v4
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Update README
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |-
        python build_readme.py
        cat README.md
    - name: Commit and push if changed
      run: |-
        git diff
        git config --global user.email "mamboer@gmail.com"
        git config --global user.name "mamboer-bot"
        git pull
        git add -A
        git commit -m "chore: Updated content" || exit 0
        git push
